CREATE TABLE subscriber
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    birth_date date,
    gender     VARCHAR(255)                            NOT NULL,
    join_date  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_subscriber PRIMARY KEY (id)
);