CREATE TABLE subscriber_list
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    owner_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_subscriberlist PRIMARY KEY (id)
);

ALTER TABLE subscriber_list
    ADD CONSTRAINT FK_SUBSCRIBERLIST_ON_OWNER FOREIGN KEY (owner_id) REFERENCES user_app (id);