CREATE TABLE subscriber_list_entry
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_added         TIMESTAMP WITHOUT TIME ZONE,
    confirmed          BOOLEAN                                 NOT NULL,
    source             VARCHAR(255),
    subscriber_list_id BIGINT,
    subscriber_id      BIGINT,
    CONSTRAINT pk_subscriberlistentry PRIMARY KEY (id)
);

ALTER TABLE subscriber_list_entry
    ADD CONSTRAINT FK_SUBSCRIBERLISTENTRY_ON_SUBSCRIBER FOREIGN KEY (subscriber_id) REFERENCES subscriber (id);

ALTER TABLE subscriber_list_entry
    ADD CONSTRAINT FK_SUBSCRIBERLISTENTRY_ON_SUBSCRIBER_LIST FOREIGN KEY (subscriber_list_id) REFERENCES subscriber_list (id);